// web/src/components/post-actions.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { useAuth } from "./auth-context";
import { ReportDialog } from "./report-dialog";

type ActionProps = {
  targetType: string;
  targetDocumentId: string;
};

export function PostActions({ targetType, targetDocumentId }: ActionProps) {
  const { isLoggedIn, jwt, openLoginModal, authorizedFetch } = useAuth();
  const [liked, setLiked] = useState(false);
  const [likes, setLikes] = useState(0);
  const [followed, setFollowed] = useState(false);
  const [follows, setFollows] = useState(0);
  const [copied, setCopied] = useState(false);
  const [pendingAction, setPendingAction] = useState<"like" | "follow" | null>(null);
  const loadedRef = useRef(false);

  // Load counts on mount (no auth needed)
  useEffect(() => {
    fetch(
      `/api/interaction-proxy?targetType=${encodeURIComponent(targetType)}&targetDocumentId=${encodeURIComponent(targetDocumentId)}`,
    )
      .then((r) => r.json())
      .then((data) => {
        setLikes(data.likesCount ?? 0);
        setFollows(data.followsCount ?? 0);
      })
      .catch(() => {/* ignore */});
  }, [targetType, targetDocumentId]);

  // Load user's like/follow state when logged in
  useEffect(() => {
    if (!isLoggedIn || !jwt || loadedRef.current) return;
    loadedRef.current = true;

    authorizedFetch(
      `/api/interaction-proxy?targetType=${encodeURIComponent(targetType)}&targetDocumentId=${encodeURIComponent(targetDocumentId)}`,
      {}
    )
      .then((r) => r.json())
      .then((data) => {
        setLiked(!!data.liked);
        setFollowed(!!data.followed);
        setLikes(data.likesCount ?? 0);
        setFollows(data.followsCount ?? 0);
      })
      .catch(() => {/* ignore */});
  }, [isLoggedIn, jwt, targetType, targetDocumentId, authorizedFetch]);

  const toggleInteraction = async (actionType: "like" | "follow") => {
    if (!isLoggedIn || !jwt) { openLoginModal(); return; }
    if (pendingAction === actionType) return;

    setPendingAction(actionType);

    const res = await authorizedFetch("/api/interaction-proxy", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ actionType, targetType, targetDocumentId }),
    }).catch(() => null);

    try {
      if (!res?.ok) return;
      const data = await res.json();
      const active: boolean = !!data?.toggled;

      if (actionType === "like") {
        setLiked(active);
        setLikes((n) => active ? n + 1 : Math.max(0, n - 1));
      } else {
        setFollowed(active);
        setFollows((n) => active ? n + 1 : Math.max(0, n - 1));
      }
    } finally {
      setPendingAction((current) => current === actionType ? null : current);
    }
  };

  const handleLike = () => toggleInteraction("like");
  const handleFollow = () => toggleInteraction("follow");

  const handleShare = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback: do nothing
    }
  };

  return (
    <div className="flex flex-wrap gap-3 border-t border-b border-zinc-200 dark:border-zinc-800 py-4 mt-8">
      {/* Like */}
      <button
        onClick={handleLike}
        disabled={pendingAction === "like"}
        data-track-cta="post_like"
        className={`flex items-center gap-2 text-sm font-medium transition-colors px-3 py-1.5 rounded-full ${
          liked
            ? "bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400"
            : "text-zinc-600 dark:text-zinc-400 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20"
        } ${pendingAction === "like" ? "opacity-70 cursor-not-allowed" : ""}`}
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill={liked ? "currentColor" : "none"} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>
        Thích {likes > 0 && <span>({likes})</span>}
      </button>

      {/* Follow */}
      <button
        onClick={handleFollow}
        disabled={pendingAction === "follow"}
        data-track-cta="post_follow"
        className={`flex items-center gap-2 text-sm font-medium transition-colors px-3 py-1.5 rounded-full ${
          followed
            ? "bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400"
            : "text-zinc-600 dark:text-zinc-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20"
        } ${pendingAction === "follow" ? "opacity-70 cursor-not-allowed" : ""}`}
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/></svg>
        {followed ? "Đang theo dõi" : "Theo dõi"} {follows > 0 && <span>({follows})</span>}
      </button>

      {/* Report */}
      <ReportDialog targetType={targetType} targetDocumentId={targetDocumentId} />

      {/* Share / Copy link */}
      <button
        onClick={handleShare}
        data-track-cta="post_share"
        className={`flex items-center gap-2 text-sm font-medium transition-colors px-3 py-1.5 rounded-full ${
          copied
            ? "bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400"
            : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:bg-zinc-100 dark:hover:bg-zinc-800"
        }`}
      >
        {copied ? (
          <>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></svg>
            Đã sao chép!
          </>
        ) : (
          <>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/></svg>
            Chia sẻ
          </>
        )}
      </button>
    </div>
  );
}

// web-nuxt/app/components/PostActions.vue
<template>
  <div :class="wrapperClass">
    <button
      type="button"
      class="flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-medium transition-colors"
      :class="likeClass"
      :disabled="pendingAction === 'like'"
      @click="toggleInteraction('like')"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" :fill="liked ? 'currentColor' : 'none'" stroke="currentColor" stroke-width="2">
        <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
      </svg>
      Thich <span v-if="likes > 0">({{ likes }})</span>
    </button>

    <button
      type="button"
      class="flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-medium transition-colors"
      :class="followClass"
      :disabled="pendingAction === 'follow'"
      @click="toggleInteraction('follow')"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <line x1="19" x2="19" y1="8" y2="14" />
        <line x1="22" x2="16" y1="11" y2="11" />
      </svg>
      {{ followed ? "Dang theo doi" : "Theo doi" }} <span v-if="follows > 0">({{ follows }})</span>
    </button>

    <ReportDialog :target-type="targetType" :target-document-id="targetDocumentId" />

    <button
      type="button"
      class="flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-medium transition-colors"
      :class="shareClass"
      @click="handleShare"
    >
      {{ copied ? "Da sao chep!" : "Chia se" }}
    </button>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  targetType: string;
  targetDocumentId: string;
}>();

const auth = useAuth();
const theme = useTheme();
const liked = ref(false);
const likes = ref(0);
const followed = ref(false);
const follows = ref(0);
const copied = ref(false);
const pendingAction = ref<"like" | "follow" | null>(null);
const wrapperClass = computed(() => (theme.isDark.value ? "mt-8 flex flex-wrap gap-3 border-b border-t border-zinc-800 py-4" : "mt-8 flex flex-wrap gap-3 border-b border-t border-zinc-200 py-4"));
const likeClass = computed(() => {
  if (liked.value) {
    return theme.isDark.value ? "bg-red-900/20 text-red-400" : "bg-red-50 text-red-600";
  }
  return theme.isDark.value ? "text-zinc-400 hover:bg-red-500/10 hover:text-red-300" : "text-zinc-600 hover:bg-red-50 hover:text-red-600";
});
const followClass = computed(() => {
  if (followed.value) {
    return theme.isDark.value ? "bg-blue-900/20 text-blue-400" : "bg-blue-50 text-blue-600";
  }
  return theme.isDark.value ? "text-zinc-400 hover:bg-blue-500/10 hover:text-blue-300" : "text-zinc-600 hover:bg-blue-50 hover:text-blue-600";
});
const shareClass = computed(() => {
  if (copied.value) {
    return theme.isDark.value ? "bg-green-900/20 text-green-400" : "bg-green-50 text-green-600";
  }
  return theme.isDark.value ? "text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100" : "text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900";
});

async function loadState() {
  if (!auth.isHydrated.value) return;
  if (!auth.isLoggedIn.value) {
    liked.value = false;
    followed.value = false;
    likes.value = 0;
    follows.value = 0;
    return;
  }
  try {
    const response = await auth.authorizedFetch(`/api/interaction-proxy?targetType=${encodeURIComponent(props.targetType)}&targetDocumentId=${encodeURIComponent(props.targetDocumentId)}`, { cache: "no-store" });
    if (!response.ok) return;
    const payload = await response.json();
    likes.value = payload.likesCount ?? 0;
    follows.value = payload.followsCount ?? 0;
    liked.value = !!payload.liked;
    followed.value = !!payload.followed;
  } catch {
    // ignore
  }
}

watchEffect(() => {
  if (!auth.isHydrated.value) return;
  void loadState();
});

async function toggleInteraction(actionType: "like" | "follow") {
  if (!auth.isLoggedIn.value) {
    auth.openLoginModal();
    return;
  }
  if (pendingAction.value === actionType) return;
  pendingAction.value = actionType;
  const response = await auth.authorizedFetch("/api/interaction-proxy", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      actionType,
      targetType: props.targetType,
      targetDocumentId: props.targetDocumentId,
    }),
  });
  try {
    if (!response.ok) return;
    const payload = await response.json().catch(() => ({}));
    const active = !!payload?.toggled;
    if (actionType === "like") {
      liked.value = active;
      likes.value = active ? likes.value + 1 : Math.max(0, likes.value - 1);
      return;
    }
    followed.value = active;
    follows.value = active ? follows.value + 1 : Math.max(0, follows.value - 1);
  } finally {
    pendingAction.value = null;
  }
}

async function handleShare() {
  try {
    await navigator.clipboard.writeText(window.location.href);
    copied.value = true;
    window.setTimeout(() => {
      copied.value = false;
    }, 2500);
  } catch {
    // ignore
  }
}
</script>
