// web/src/components/tag-combobox.tsx
"use client";

import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { X, Loader2 } from "lucide-react";
import { useAuth } from "@/components/auth-context";

export type TagOption = { documentId: string; name: string };
export interface TagComboboxHandle {
  commitPending: () => Promise<void>;
}

type StrapiTagRow = { documentId?: string; name?: string };

export const TagCombobox = forwardRef<TagComboboxHandle, {
  selected: TagOption[];
  onChange: (tags: TagOption[]) => void;
}>(function TagCombobox({ selected, onChange }, ref) {
  const { authorizedFetch } = useAuth();
  const [query, setQuery] = useState("");
  const [suggestions, setSuggestions] = useState<TagOption[]>([]);
  const [open, setOpen] = useState(false);
  const [searching, setSearching] = useState(false);
  const [pendingCount, setPendingCount] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const selectedRef = useRef(selected);
  selectedRef.current = selected;
  const queryRef = useRef(query);
  queryRef.current = query;
  const suggestionsRef = useRef(suggestions);
  suggestionsRef.current = suggestions;

  useImperativeHandle(ref, () => ({
    async commitPending() {
      const name = queryRef.current.trim();
      if (!name) return;
      const exactMatch = suggestionsRef.current.find((s) => s.name.toLowerCase() === name.toLowerCase());
      if (exactMatch && !selectedRef.current.some((s) => s.documentId === exactMatch.documentId)) {
        addTag(exactMatch);
        return;
      }
      if (!selectedRef.current.some((s) => s.name.toLowerCase() === name.toLowerCase())) {
        await createTagAndAdd(name);
      }
    },
  }));

  // Close on outside click
  useEffect(() => {
    const handle = (e: MouseEvent | TouchEvent) => {
      if (!(e.target instanceof Node)) return;
      if (!containerRef.current?.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handle);
    document.addEventListener("touchstart", handle);
    return () => {
      document.removeEventListener("mousedown", handle);
      document.removeEventListener("touchstart", handle);
    };
  }, []);

  // Debounced search
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    const trimmed = query.trim();
    if (!trimmed) {
      setSuggestions([]);
      setOpen(false);
      return;
    }

    debounceRef.current = setTimeout(async () => {
      setSearching(true);
      try {
        const params = new URLSearchParams({ q: trimmed });
        const res = await fetch(`/api/tags-proxy?${params.toString()}`, { cache: "no-store" });
        if (!res.ok) return;
        const payload = (await res.json()) as { data?: StrapiTagRow[] };
        setSuggestions(
          (payload.data ?? [])
            .filter((t): t is { documentId: string; name: string } => !!t.documentId && !!t.name)
            .filter((t) => !selected.some((s) => s.documentId === t.documentId)),
        );
        setOpen(true);
      } finally {
        setSearching(false);
      }
    }, 300);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [query, selected]);

  const addTag = (tag: TagOption) => {
    if (selectedRef.current.some((t) => t.documentId === tag.documentId)) return;
    onChange([...selectedRef.current, tag]);
    setQuery("");
    setSuggestions([]);
    setOpen(false);
    inputRef.current?.focus();
  };

  const removeTag = (documentId: string) => {
    onChange(selected.filter((t) => t.documentId !== documentId));
  };

  const createTagAndAdd = async (name: string) => {
    setPendingCount((c) => c + 1);
    try {
      const res = await authorizedFetch("/api/tags-proxy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name }),
      });
      if (!res.ok) return;
      const payload = (await res.json()) as { data?: TagOption };
      if (payload.data?.documentId) {
        addTag({ documentId: payload.data.documentId, name: payload.data.name });
      }
    } finally {
      setPendingCount((c) => c - 1);
    }
  };

  const handleCommitCurrent = () => {
    const name = query.trim();
    if (!name) return;
    const exactMatch = suggestions.find((s) => s.name.toLowerCase() === name.toLowerCase());
    if (exactMatch && !selectedRef.current.some((s) => s.documentId === exactMatch.documentId)) {
      addTag(exactMatch);
      return;
    }
    if (!selectedRef.current.some((s) => s.name.toLowerCase() === name.toLowerCase())) {
      void createTagAndAdd(name);
    }
  };

  const trimmedQuery = query.trim();
  const exactMatch = suggestions.some((s) => s.name.toLowerCase() === trimmedQuery.toLowerCase());
  const alreadySelected = selected.some((s) => s.name.toLowerCase() === trimmedQuery.toLowerCase());
  const showCreateOption = trimmedQuery.length > 0 && !exactMatch && !alreadySelected;

  const isDropdownVisible = open && (suggestions.length > 0 || showCreateOption);

  return (
    <div ref={containerRef} className="relative">
      <div className="flex min-h-10 flex-wrap items-center gap-1 rounded-md border border-gray-200 bg-gray-50 px-3 py-2 dark:border-gray-700 dark:bg-gray-900">
        {selected.map((tag) => (
          <span
            key={tag.documentId}
            className="inline-flex items-center gap-1 rounded bg-gray-200 px-2 py-0.5 text-xs text-gray-800 dark:bg-gray-600 dark:text-gray-100"
          >
            {tag.name}
            <button
              type="button"
              aria-label={`Xóa tag ${tag.name}`}
              className="inline-flex h-3.5 w-3.5 items-center justify-center rounded hover:bg-gray-300 dark:hover:bg-gray-500"
              onClick={() => removeTag(tag.documentId)}
            >
              <X className="h-2.5 w-2.5" />
            </button>
          </span>
        ))}
        <input
          ref={inputRef}
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => trimmedQuery && setOpen(true)}
          onBlur={() => handleCommitCurrent()}
          onKeyDown={(e) => {
            if (e.key === "," || e.key === "Enter") {
              e.preventDefault();
              handleCommitCurrent();
            } else if (e.key === "Backspace" && query === "" && selected.length > 0) {
              onChange(selected.slice(0, -1));
            }
          }}
          placeholder={selected.length === 0 ? "Gõ để tìm hoặc tạo tag..." : "Thêm tag..."}
          className="min-w-[120px] flex-1 bg-transparent text-sm text-gray-800 outline-none placeholder:text-gray-400 dark:text-gray-100 dark:placeholder:text-gray-500"
        />
        {(searching || pendingCount > 0) && <Loader2 className="h-4 w-4 animate-spin text-gray-400" />}
      </div>

      {isDropdownVisible && (
        <div className="absolute z-30 mt-1 w-full overflow-hidden rounded-md border border-gray-200 bg-white shadow-md dark:border-gray-700 dark:bg-gray-800">
          {suggestions.map((tag) => (
            <button
              key={tag.documentId}
              type="button"
              className="flex w-full items-center px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
              onClick={() => addTag(tag)}
            >
              {tag.name}
            </button>
          ))}
          {showCreateOption && (
            <button
              type="button"
              className="flex w-full items-center gap-1.5 px-3 py-2 text-left text-sm text-blue-600 hover:bg-gray-100 dark:text-blue-400 dark:hover:bg-gray-700"
              onClick={() => void createTagAndAdd(trimmedQuery)}
              disabled={pendingCount > 0}
            >
              <span className="font-medium">+ Tạo tag</span>
              <span className="truncate">&ldquo;{trimmedQuery}&rdquo;</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
});

// web-nuxt/app/components/TagCombobox.vue
<template>
  <div ref="containerEl" class="relative">
    <div class="flex min-h-10 flex-wrap items-center gap-1 rounded-md border border-gray-200 bg-gray-50 px-3 py-2">
      <span
        v-for="tag in model"
        :key="tag.documentId"
        class="inline-flex items-center gap-1 rounded bg-gray-200 px-2 py-0.5 text-xs text-gray-800"
      >
        {{ tag.name }}
        <button type="button" :aria-label="`Xóa tag ${tag.name}`" class="inline-flex h-4 w-4 items-center justify-center rounded hover:bg-gray-300" @click="removeTag(tag.documentId)">
          ×
        </button>
      </span>

      <input
        ref="inputEl"
        v-model="query"
        type="text"
        class="min-w-[120px] flex-1 bg-transparent text-sm text-gray-800 outline-none placeholder:text-gray-400"
        :placeholder="model.length === 0 ? 'Gõ để tìm hoặc tạo tag...' : 'Thêm tag...'"
        @focus="trimmedQuery && (open = true)"
        @blur="handleCommitCurrent"
        @keydown="handleKeyDown"
      />

      <svg v-if="searching || pendingCount > 0" class="h-4 w-4 animate-spin text-gray-400" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21 12a9 9 0 1 1-6.219-8.56" />
      </svg>
    </div>

    <div v-if="isDropdownVisible" class="absolute z-30 mt-1 w-full overflow-hidden rounded-md border border-gray-200 bg-white shadow-md">
      <button
        v-for="tag in suggestions"
        :key="tag.documentId"
        type="button"
        class="flex w-full items-center px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-100"
        @mousedown.prevent="addTag(tag)"
      >
        {{ tag.name }}
      </button>

      <button
        v-if="showCreateOption"
        type="button"
        class="flex w-full items-center gap-1.5 px-3 py-2 text-left text-sm text-blue-600 hover:bg-gray-100 disabled:opacity-60"
        :disabled="pendingCount > 0"
        @mousedown.prevent="createTagAndAdd(trimmedQuery)"
      >
        <span class="font-medium">+ Tạo tag</span>
        <span class="truncate">"{{ trimmedQuery }}"</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { TagOption } from "~~/shared/types";

const model = defineModel<TagOption[]>({ default: [] });
const auth = useAuth();
const query = ref("");
const suggestions = ref<TagOption[]>([]);
const open = ref(false);
const searching = ref(false);
const pendingCount = ref(0);
const containerEl = ref<HTMLElement | null>(null);
const inputEl = ref<HTMLInputElement | null>(null);
let outsideHandler: ((event: MouseEvent | TouchEvent) => void) | null = null;

const trimmedQuery = computed(() => query.value.trim());
const exactMatch = computed(() => suggestions.value.some((tag) => tag.name.toLowerCase() === trimmedQuery.value.toLowerCase()));
const alreadySelected = computed(() => model.value.some((tag) => tag.name.toLowerCase() === trimmedQuery.value.toLowerCase()));
const showCreateOption = computed(() => trimmedQuery.value.length > 0 && !exactMatch.value && !alreadySelected.value);
const isDropdownVisible = computed(() => open.value && (suggestions.value.length > 0 || showCreateOption.value));

function resetInput() {
  query.value = "";
  suggestions.value = [];
  open.value = false;
  inputEl.value?.focus();
}

function addTag(tag: TagOption) {
  if (model.value.some((item) => item.documentId === tag.documentId)) return;
  model.value = [...model.value, tag];
  resetInput();
}

function removeTag(documentId: string) {
  model.value = model.value.filter((tag) => tag.documentId !== documentId);
}

async function createTagAndAdd(name: string) {
  pendingCount.value += 1;
  try {
    const response = await auth.authorizedFetch("/api/tags-proxy", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name }),
    });
    if (response.status === 401) {
      auth.openLoginModal();
      return;
    }
    if (!response.ok) return;
    const payload = (await response.json().catch(() => ({}))) as {
      data?: TagOption;
      document_id?: string;
      documentId?: string;
      name?: string;
      slug?: string;
    };
    const created = payload.data ?? {
      documentId: payload.document_id ?? payload.documentId ?? "",
      name: payload.name ?? "",
      slug: payload.slug,
    };
    if (created.documentId && created.name && !model.value.some((item) => item.documentId === created.documentId)) {
      addTag(created);
    }
  } finally {
    pendingCount.value -= 1;
  }
}

async function commitPending() {
  const name = query.value.trim();
  if (!name) return;
  const matched = suggestions.value.find((tag) => tag.name.toLowerCase() === name.toLowerCase());
  if (matched && !model.value.some((tag) => tag.documentId === matched.documentId)) {
    addTag(matched);
    return;
  }
  if (!model.value.some((tag) => tag.name.toLowerCase() === name.toLowerCase())) {
    await createTagAndAdd(name);
  }
}

function handleCommitCurrent() {
  void commitPending();
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === "," || event.key === "Enter") {
    event.preventDefault();
    handleCommitCurrent();
  } else if (event.key === "Backspace" && query.value === "" && model.value.length > 0) {
    model.value = model.value.slice(0, -1);
  }
}

watch(
  trimmedQuery,
  (nextValue, _prev, onCleanup) => {
    if (!nextValue) {
      suggestions.value = [];
      open.value = false;
      return;
    }

    const timer = window.setTimeout(async () => {
      searching.value = true;
      try {
        const payload = await $fetch<{ data?: TagOption[] }>(`/api/tags-proxy?q=${encodeURIComponent(nextValue)}`, { cache: "no-store" });
        suggestions.value = (payload.data ?? []).filter((tag) => !model.value.some((item) => item.documentId === tag.documentId));
        open.value = true;
      } finally {
        searching.value = false;
      }
    }, 300);

    onCleanup(() => window.clearTimeout(timer));
  },
  { flush: "post" },
);

onMounted(() => {
  outsideHandler = (event: MouseEvent | TouchEvent) => {
    if (!(event.target instanceof Node)) return;
    if (!containerEl.value?.contains(event.target)) {
      open.value = false;
    }
  };
  document.addEventListener("mousedown", outsideHandler);
  document.addEventListener("touchstart", outsideHandler);
});

onBeforeUnmount(() => {
  if (outsideHandler) {
    document.removeEventListener("mousedown", outsideHandler);
    document.removeEventListener("touchstart", outsideHandler);
  }
});

defineExpose({ commitPending });
</script>
