// web/src/app/p/[id]/page.tsx
import { notFound, permanentRedirect } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { getCommentsForTarget, getPostByRouteId } from "@/lib/strapi";
import { RichTextWithLightbox } from "@/components/rich-text-with-lightbox";
import { PostViewGallery } from "@/components/post-view-gallery";
import { PostActions } from "@/components/post-actions";
import { GenericComments } from "@/components/generic-comments";
import { SITE_URL, SITE_NAME, stripHtml, truncate, toAbsoluteMediaUrl, extractFirstImageFromHtml, buildOgImages } from "@/lib/seo";

export const dynamic = "force-dynamic";

function relativeTime(dateStr: string) {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  const hours = Math.floor(mins / 60);
  const days = Math.floor(hours / 24);
  const weeks = Math.floor(days / 7);
  const months = Math.floor(days / 30);
  const years = Math.floor(days / 365);
  if (mins < 1) return "vừa xong";
  if (mins < 60) return `${mins} phút trước`;
  if (hours < 24) return `${hours} giờ trước`;
  if (days < 7) return `${days} ngày trước`;
  if (weeks < 4) return `${weeks} tuần trước`;
  if (months < 12) return `${months} tháng trước`;
  return `${years} năm trước`;
}

type PostPageProps = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: PostPageProps): Promise<Metadata> {
  const { id } = await params;
  const post = await getPostByRouteId(id);
  if (!post) return {};

  const description = truncate(stripHtml(post.content ?? ""), 160);
  const canonical = `${SITE_URL}/p/${post.slug}--${post.documentId}`;
  const imageUrl =
    toAbsoluteMediaUrl(post.images?.[0]?.url) ??
    extractFirstImageFromHtml(post.content ?? "");

  return {
    title: post.title,
    description,
    alternates: { canonical },
    other: {
      "trekky:page_type": "article",
      "trekky:content_id": post.documentId,
      "trekky:content_slug": post.slug,
      "trekky:content_title": post.title,
      "trekky:author": post.author?.username ?? "",
      "trekky:category": post.categories?.[0]?.name ?? "",
      "trekky:tags": post.tags?.map((t) => t.name).join(",") ?? "",
    },
    openGraph: {
      type: "article",
      url: canonical,
      title: post.title,
      description,
      siteName: SITE_NAME,
      locale: "vi_VN",
      images: buildOgImages(imageUrl, post.title),
      publishedTime: post.publishedAt,
      authors: post.author?.username ? [`${SITE_URL}/u/${post.author.username}`] : undefined,
      tags: post.tags?.map((t) => t.name),
      section: post.categories?.[0]?.name,
    },
    twitter: {
      card: imageUrl ? "summary_large_image" : "summary",
      title: post.title,
      description,
      images: imageUrl ? [imageUrl] : undefined,
    },
  };
}

export default async function PostPage({ params }: PostPageProps) {
  const { id } = await params;
  const post = await getPostByRouteId(id);

  if (!post) {
    notFound();
  }

  const canonicalId = `${post.slug}--${post.documentId}`;
  if (id !== canonicalId) {
    permanentRedirect(`/p/${canonicalId}`);
  }

  const comments = await getCommentsForTarget("post", post.documentId);

  const formattedDate = post.createdAt
    ? relativeTime(post.createdAt)
    : post.publishedAt
      ? relativeTime(post.publishedAt)
      : null;
  const createdAtMs = post.createdAt ? new Date(post.createdAt).getTime() : null;
  const updatedAtMs = post.updatedAt ? new Date(post.updatedAt).getTime() : null;
  const isUpdated = !!createdAtMs && !!updatedAtMs && updatedAtMs - createdAtMs > 60 * 1000;
  const updatedLabel = isUpdated && post.updatedAt ? relativeTime(post.updatedAt) : null;
  const authorInitial = (post.author?.username ?? "?")[0]?.toUpperCase() ?? "?";
  const authorAvatarUrl = toAbsoluteMediaUrl(post.author?.avatar?.url);
  const categories = post.categories ?? [];
  const tags = post.tags ?? [];

  return (
    <article className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden dark:bg-gray-800 dark:border-gray-700">
      <div className="px-6 pt-5 pb-5">

        {/* 1. Categories */}
        {categories.length > 0 && (
          <div className="flex flex-wrap items-center gap-1 text-xs text-gray-500 mb-3">
            {categories.map((cat, i) => (
              <span key={cat.documentId} className="flex items-center gap-1">
                {i > 0 && <span className="text-gray-300 dark:text-gray-600">·</span>}
                <Link
                  href={`/c/${cat.slug}`}
                  data-track-cta={`post_category_${cat.slug}`}
                  className="hover:text-gray-700 hover:underline transition-colors font-medium dark:hover:text-gray-300"
                >
                  {cat.name}
                </Link>
              </span>
            ))}
          </div>
        )}

        {/* 2. Title */}
        <h1 className="text-2xl font-bold text-gray-900 leading-snug dark:text-gray-100">{post.title}</h1>

        {/* 3. Author + time */}
        <div className="flex items-center gap-2 mt-3">
          <Link href={post.author?.username ? `/u/${post.author.username}` : "#"} className="shrink-0">
            {authorAvatarUrl ? (
              <Image
                src={authorAvatarUrl}
                alt={post.author?.username ?? "User avatar"}
                width={32}
                height={32}
                className="w-8 h-8 rounded-full object-cover bg-gray-300 dark:bg-gray-600"
                unoptimized
              />
            ) : (
              <div className="w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center text-gray-600 font-bold text-xs dark:bg-gray-600 dark:text-gray-300">
                {authorInitial}
              </div>
            )}
          </Link>
          <div className="flex items-center gap-1.5 text-sm text-gray-500 dark:text-gray-400">
            <Link
              href={post.author?.username ? `/u/${post.author.username}` : "#"}
              data-track-cta="post_author_profile"
              className="font-medium text-gray-700 hover:text-gray-900 transition-colors dark:text-gray-300 dark:hover:text-gray-100"
            >
              {post.author?.username ?? "Ẩn danh"}
            </Link>
            {formattedDate && (
              <>
                <span className="text-gray-300 dark:text-gray-600">·</span>
                <span>{formattedDate}</span>
              </>
            )}
            {updatedLabel && (
              <>
                <span className="text-gray-300 dark:text-gray-600">•</span>
                <span>Cập nhật: {updatedLabel}</span>
              </>
            )}
          </div>
        </div>
      </div>

      {/* 4. Gallery */}
      {(post.images?.length ?? 0) > 0 && (
        <div className="px-6 pb-5">
          <PostViewGallery images={post.images!} />
        </div>
      )}

      {/* 5. Content */}
      <div className="px-6 pb-6">
        <RichTextWithLightbox
          html={post.content}
          className="prose prose-sm max-w-none text-gray-700 dark:text-gray-300 [&_img]:rounded-lg [&_img]:my-3 [&_img]:max-w-full [&_a]:text-blue-600 [&_a:hover]:text-blue-800 dark:[&_a]:text-blue-400 dark:[&_a:hover]:text-blue-300 [&_pre]:bg-gray-50 dark:[&_pre]:bg-gray-900 [&_pre]:rounded-lg [&_pre]:p-4 [&_blockquote]:border-l-4 [&_blockquote]:border-gray-300 dark:[&_blockquote]:border-gray-600 [&_blockquote]:pl-4 [&_blockquote]:text-gray-600 dark:[&_blockquote]:text-gray-400"
        />
      </div>

      {/* 6. Tags */}
      {tags.length > 0 && (
        <div className="px-6 pb-5 flex flex-wrap gap-1.5">
          {tags.map((tag) => (
            <Link
              key={tag.documentId}
              href={`/t/${tag.slug}`}
              data-track-cta={`post_tag_${tag.slug}`}
              className="inline-flex items-center px-2.5 py-0.5 rounded-full bg-gray-100 text-xs text-gray-500 hover:bg-gray-200 hover:text-gray-700 transition-colors dark:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-gray-200"
            >
              #{tag.name}
            </Link>
          ))}
        </div>
      )}

      {/* 7. Actions */}
      <div className="px-6 border-t border-gray-100 dark:border-gray-700">
        <PostActions targetType="post" targetDocumentId={post.documentId} />
      </div>

      {/* 8. Comments */}
      <div className="px-6 pb-6 pt-5">
        <h2 className="mb-4 text-sm font-semibold text-gray-700 dark:text-zinc-200">
          Bình luận{" "}
          {comments.length > 0 && (
            <span className="text-gray-400 font-normal">({comments.length})</span>
          )}
        </h2>
        <GenericComments
          targetType="post"
          targetDocumentId={post.documentId}
          initialComments={comments}
        />
      </div>
    </article>
  );
}

// web-nuxt/app/pages/p/[id].vue
<template>
  <article v-if="post" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div class="px-6 pt-5 pb-5">
      <div v-if="post.categories?.length" class="mb-3 flex flex-wrap items-center gap-1 text-xs text-slate-500">
        <span v-for="(category, index) in post.categories" :key="category.documentId" class="flex items-center gap-1">
          <span v-if="index > 0" class="text-slate-300">·</span>
          <NuxtLink :to="`/c/${category.slug}`" class="font-medium hover:text-slate-800 hover:underline">{{ category.name }}</NuxtLink>
        </span>
      </div>

      <h1 class="text-2xl font-bold leading-snug text-slate-900">{{ post.title }}</h1>

      <div class="mt-3 flex items-center gap-2">
        <img v-if="authorAvatarUrl" :src="authorAvatarUrl" :alt="post.author?.username || 'avatar'" class="h-8 w-8 rounded-full object-cover bg-slate-300" />
        <div v-else class="flex h-8 w-8 items-center justify-center rounded-full bg-slate-300 text-xs font-bold text-slate-600">
          {{ authorInitial }}
        </div>
        <div class="flex items-center gap-1.5 text-sm text-slate-500">
          <NuxtLink :to="post.author?.username ? `/u/${post.author.username}` : '#'" class="font-medium text-slate-700 hover:text-slate-900">
            {{ post.author?.username ?? "An danh" }}
          </NuxtLink>
          <span v-if="formattedDate">·</span>
          <span v-if="formattedDate">{{ formattedDate }}</span>
        </div>
      </div>
    </div>

    <div v-if="(post.images?.length ?? 0) > 0" class="px-6 pb-5">
      <PostViewGallery :images="post.images ?? []" />
    </div>

    <div class="px-6 pb-6">
      <RichTextWithLightbox :html="post.content" />
    </div>

    <div v-if="post.tags?.length" class="flex flex-wrap gap-1.5 px-6 pb-5">
      <NuxtLink
        v-for="tag in post.tags"
        :key="tag.documentId"
        :to="`/t/${tag.slug}`"
        class="inline-flex items-center rounded-full bg-slate-100 px-2.5 py-0.5 text-xs text-slate-500 hover:bg-slate-200 hover:text-slate-700"
      >
        #{{ tag.name }}
      </NuxtLink>
    </div>

    <div class="border-t border-slate-100 px-6">
      <PostActions target-type="post" :target-document-id="post.documentId" />
    </div>

    <div class="px-6 pb-6 pt-5">
      <h2 class="mb-4 text-sm font-semibold text-slate-700">
        Binh luan <span v-if="comments.length" class="font-normal text-slate-400">({{ comments.length }})</span>
      </h2>
      <GenericComments target-type="post" :target-document-id="post.documentId" :initial-comments="comments" />
    </div>
  </article>
</template>

<script setup lang="ts">
import { buildOgImages, extractFirstImageFromHtml, SITE_NAME, stripHtml, toAbsoluteMediaUrl, truncate } from "~~/shared/seo";
import type { Comment, Post } from "~~/shared/types";

const route = useRoute();
const router = useRouter();
const config = useRuntimeConfig();
const id = route.params.id as string;

const [{ data: postData }, { data: commentsData }] = await Promise.all([
  useFetch<Post | null>(`/api/internal/post/${encodeURIComponent(id)}`),
  useFetch<Comment[]>(`/api/internal/post-comments/${encodeURIComponent(id)}`),
]);

const post = computed(() => postData.value);
if (!post.value) throw createError({ statusCode: 404, statusMessage: "Post not found" });

const canonicalId = `${post.value.slug}--${post.value.documentId}`;
if (id !== canonicalId && import.meta.client) {
  router.replace(`/p/${canonicalId}`);
}

const comments = computed(() => commentsData.value ?? []);
const authorAvatarUrl = computed(() => toAbsoluteMediaUrl(post.value?.author?.avatar?.url, config.public.apiUrl) ?? "");
const authorInitial = computed(() => (post.value?.author?.username ?? "?").slice(0, 1).toUpperCase());
const formattedDate = computed(() => {
  const source = post.value?.createdAt || post.value?.publishedAt;
  return source ? new Date(source).toLocaleString("vi-VN") : "";
});
const description = computed(() => truncate(stripHtml(post.value?.content ?? ""), 160));
const imageUrl = computed(
  () => toAbsoluteMediaUrl(post.value?.images?.[0]?.url, config.public.apiUrl) ?? extractFirstImageFromHtml(post.value?.content ?? "", config.public.apiUrl),
);

useSeoMeta({
  title: post.value.title,
  description: description.value,
  ogTitle: post.value.title,
  ogDescription: description.value,
  ogType: "article",
  ogSiteName: SITE_NAME,
  ogImage: buildOgImages(imageUrl.value, config.public.siteUrl, post.value.title)[0].url,
});
</script>
