// web/src/app/search/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { SITE_URL, sanitizeRichHtml } from "@/lib/seo";

export const dynamic = "force-dynamic";

type SearchPageProps = {
  searchParams: Promise<{ q?: string }>;
};

type PostHit = {
  id: number;
  documentId: string;
  title: string;
  slug: string;
  excerpt?: string;
  publishedAt: string;
};

type TagHit = {
  id: number;
  documentId: string;
  name: string;
  slug: string;
  description?: string;
};

type CategoryHit = {
  id: number;
  documentId: string;
  name: string;
  slug: string;
  description?: string;
};

type SearchResults = {
  posts: PostHit[];
  tags: TagHit[];
  categories: CategoryHit[];
};

async function fetchSearchResults(q: string): Promise<SearchResults> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
  const res = await fetch(`${baseUrl}/api/search-proxy?q=${encodeURIComponent(q)}`, {
    cache: "no-store",
  });
  if (!res.ok) return { posts: [], tags: [], categories: [] };
  return res.json();
}

export async function generateMetadata({ searchParams }: SearchPageProps): Promise<Metadata> {
  const { q } = await searchParams;
  const query = q?.trim() || "";
  const canonical = query ? `${SITE_URL}/search?q=${encodeURIComponent(query)}` : `${SITE_URL}/search`;

  return {
    title: query ? `Tìm kiếm: ${query}` : "Tìm kiếm",
    description: query ? `Kết quả tìm kiếm cho "${query}"` : "Tìm kiếm bài viết, tag và danh mục",
    alternates: { canonical },
    robots: {
      index: false,
      follow: false,
      googleBot: {
        index: false,
        follow: false,
        noimageindex: true,
      },
    },
  };
}

export default async function SearchPage({ searchParams }: SearchPageProps) {
  const { q } = await searchParams;
  const query = q?.trim() || "";

  let results: SearchResults = { posts: [], tags: [], categories: [] };
  if (query) {
    results = await fetchSearchResults(query);
  }

  const totalResults = results.posts.length + results.tags.length + results.categories.length;

  return (
    <div className="space-y-4">
      <section className="overflow-hidden rounded-lg border border-gray-200 bg-white px-6 py-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 sm:text-3xl">
          {query ? "Kết quả tìm kiếm" : "Tìm kiếm"}
        </h1>
        {query && (
          <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
            {totalResults > 0
              ? `${totalResults} kết quả cho "${query}"`
              : `Không tìm thấy kết quả nào cho "${query}"`}
          </p>
        )}
        <div className="mt-4 border-t border-gray-200 pt-4 dark:border-gray-700">
          <Link href="/" className="text-sm text-gray-600 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100">
            &larr; Về trang chủ
          </Link>
        </div>
      </section>

      {!query && (
        <div className="rounded-lg border border-gray-200 bg-white px-6 py-10 text-center shadow-sm dark:border-gray-700 dark:bg-gray-800">
          <p className="text-gray-500 dark:text-gray-400">Nhập từ khóa vào ô tìm kiếm để bắt đầu</p>
        </div>
      )}

      {query && totalResults === 0 && (
        <div className="rounded-lg border border-gray-200 bg-white px-6 py-10 text-center shadow-sm dark:border-gray-700 dark:bg-gray-800">
          <p className="text-gray-500 dark:text-gray-400">Không tìm thấy kết quả nào phù hợp</p>
        </div>
      )}

      {results.posts.length > 0 && (
        <section className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">
          <div className="border-b border-gray-100 px-5 py-3 dark:border-gray-700">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
              Bài viết ({results.posts.length})
            </h2>
          </div>
          <ul className="divide-y divide-gray-100 dark:divide-gray-700">
            {results.posts.map((post, index) => (
              <li key={`post-${post.documentId}-${post.slug}-${index}`}>
                <Link
                  href={`/p/${post.slug}--${post.documentId}`}
                  className="block px-5 py-4 transition-colors hover:bg-gray-50 dark:hover:bg-gray-700/50"
                >
                  <p className="font-medium text-gray-900 dark:text-gray-100">{post.title}</p>
                  {post.excerpt && (
                    <div
                      className="mt-1 line-clamp-2 text-sm text-gray-600 dark:text-gray-400 [&_p]:inline"
                      dangerouslySetInnerHTML={{ __html: sanitizeRichHtml(post.excerpt) }}
                    />
                  )}
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      {results.tags.length > 0 && (
        <section className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">
          <div className="border-b border-gray-100 px-5 py-3 dark:border-gray-700">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
              Tags ({results.tags.length})
            </h2>
          </div>
          <ul className="flex flex-wrap gap-2 p-5">
            {results.tags.map((tag) => (
              <li key={tag.documentId}>
                <Link
                  href={`/t/${tag.slug}`}
                  className="inline-flex items-center rounded-full bg-gray-100 px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600"
                >
                  #{tag.name}
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      {results.categories.length > 0 && (
        <section className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">
          <div className="border-b border-gray-100 px-5 py-3 dark:border-gray-700">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
              Danh mục ({results.categories.length})
            </h2>
          </div>
          <ul className="divide-y divide-gray-100 dark:divide-gray-700">
            {results.categories.map((cat) => (
              <li key={cat.documentId}>
                <Link
                  href={`/c/${cat.slug}`}
                  className="block px-5 py-4 transition-colors hover:bg-gray-50 dark:hover:bg-gray-700/50"
                >
                  <p className="font-medium text-gray-900 dark:text-gray-100">{cat.name}</p>
                  {cat.description && (
                    <p className="mt-0.5 text-sm text-gray-600 dark:text-gray-400">{cat.description}</p>
                  )}
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

// web-nuxt/app/pages/search.vue
<template>
  <div class="space-y-4">
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white px-6 py-6 shadow-sm">
      <h1 class="text-2xl font-bold text-slate-900 sm:text-3xl">{{ query ? "Kết quả tìm kiếm" : "Tìm kiếm" }}</h1>
      <p v-if="query" class="mt-1 text-sm text-slate-600">
        {{ totalResults > 0 ? `${totalResults} kết quả cho "${query}"` : `Không tìm thấy kết quả nào cho "${query}"` }}
      </p>
    </section>

    <div v-if="!query" class="rounded-2xl border border-slate-200 bg-white px-6 py-10 text-center shadow-sm">
      <p class="text-slate-500">Nhập từ khóa vào ô tìm kiếm để bắt đầu.</p>
    </div>

    <div v-else-if="totalResults === 0" class="rounded-2xl border border-slate-200 bg-white px-6 py-10 text-center shadow-sm">
      <p class="text-slate-500">Không tìm thấy kết quả phù hợp.</p>
    </div>

    <section v-if="results.posts?.length" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div class="border-b border-slate-100 px-5 py-3">
        <h2 class="text-sm font-semibold uppercase tracking-wide text-slate-500">Bài viết ({{ results.posts.length }})</h2>
      </div>
      <ul class="divide-y divide-slate-100">
        <li v-for="post in results.posts" :key="post.documentId">
          <NuxtLink :to="`/p/${post.slug}--${post.documentId}`" class="block px-5 py-4 hover:bg-slate-50">
            <p class="font-medium text-slate-900">{{ post.title }}</p>
            <div v-if="post.excerpt" class="mt-1 line-clamp-2 text-sm text-slate-600" v-html="sanitize(post.excerpt)" />
          </NuxtLink>
        </li>
      </ul>
    </section>

    <section v-if="results.tags?.length" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div class="border-b border-slate-100 px-5 py-3">
        <h2 class="text-sm font-semibold uppercase tracking-wide text-slate-500">Tags ({{ results.tags.length }})</h2>
      </div>
      <ul class="flex flex-wrap gap-2 p-5">
        <li v-for="tag in results.tags" :key="tag.documentId">
          <NuxtLink :to="`/t/${tag.slug}`" class="inline-flex items-center rounded-full bg-slate-100 px-3 py-1.5 text-sm font-medium text-slate-700 hover:bg-slate-200">
            #{{ tag.name }}
          </NuxtLink>
        </li>
      </ul>
    </section>

    <section v-if="results.categories?.length" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div class="border-b border-slate-100 px-5 py-3">
        <h2 class="text-sm font-semibold uppercase tracking-wide text-slate-500">Danh mục ({{ results.categories.length }})</h2>
      </div>
      <ul class="divide-y divide-slate-100">
        <li v-for="category in results.categories" :key="category.documentId">
          <NuxtLink :to="`/c/${category.slug}`" class="block px-5 py-4 hover:bg-slate-50">
            <p class="font-medium text-slate-900">{{ category.name }}</p>
            <p v-if="category.description" class="mt-0.5 text-sm text-slate-600">{{ category.description }}</p>
          </NuxtLink>
        </li>
      </ul>
    </section>
  </div>
</template>

<script setup lang="ts">
import { buildCanonicalUrl, sanitizeRichHtml } from "~~/shared/seo";

type SearchResults = {
  posts: Array<{ documentId: string; title: string; slug: string; excerpt?: string }>;
  tags: Array<{ documentId: string; name: string; slug: string; description?: string }>;
  categories: Array<{ documentId: string; name: string; slug: string; description?: string }>;
};

const route = useRoute();
const config = useRuntimeConfig();
const query = computed(() => (typeof route.query.q === "string" ? route.query.q.trim() : ""));
const { data: resultsData } = await useFetch<SearchResults>(() => (query.value ? `/api/search-proxy?q=${encodeURIComponent(query.value)}` : "/api/search-proxy"));
const results = computed(() => resultsData.value ?? { posts: [], tags: [], categories: [] });
const totalResults = computed(() => (results.value.posts?.length ?? 0) + (results.value.tags?.length ?? 0) + (results.value.categories?.length ?? 0));
const canonicalUrl = computed(() =>
  query.value ? buildCanonicalUrl(`/search?q=${encodeURIComponent(query.value)}`, config.public.siteUrl) : buildCanonicalUrl("/search", config.public.siteUrl),
);

function sanitize(html: string) {
  return sanitizeRichHtml(html, config.public.apiUrl);
}

useSeoMeta({
  title: query.value ? `Tìm kiếm: ${query.value}` : "Tìm kiếm",
  description: query.value ? `Kết quả tìm kiếm cho "${query.value}"` : "Tìm kiếm bài viết, tag và danh mục",
  robots: "noindex,nofollow",
});

useHead({
  link: [
    {
      rel: "canonical",
      href: canonicalUrl.value,
    },
  ],
});
</script>
