// web-nuxt/app/pages/connect/google/callback.vue
<template>
  <div v-if="!accessToken && !errorParam" class="flex min-h-screen items-center justify-center">
    <div class="space-y-3 text-center">
      <p class="font-medium text-red-500">Không nhận được token từ Google.</p>
      <button class="text-sm text-blue-600 hover:underline" @click="router.replace(resolveNextPath(nextParam))">Quay lại</button>
    </div>
  </div>
  <div v-else-if="error" class="flex min-h-screen items-center justify-center">
    <div class="space-y-3 text-center">
      <p class="font-medium text-red-500">{{ error }}</p>
      <button class="text-sm text-blue-600 hover:underline" @click="router.replace(resolveNextPath(nextParam))">Quay lại</button>
    </div>
  </div>
  <div v-else class="flex min-h-screen items-center justify-center">
    <div class="space-y-3 text-center">
      <svg class="mx-auto animate-spin text-blue-600" xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21 12a9 9 0 1 1-6.219-8.56" />
      </svg>
      <p class="text-sm text-zinc-500">Đang xử lý đăng nhập...</p>
    </div>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();
const router = useRouter();
const auth = useAuth();
const error = ref<string | null>(null);
const accessToken = computed(() => (typeof route.query.access_token === "string" ? route.query.access_token : null));
const refreshToken = computed(() => (typeof route.query.refresh_token === "string" ? route.query.refresh_token : undefined));
const errorParam = computed(() => (typeof route.query.error === "string" ? route.query.error : null));
const nextParam = computed(() => (typeof route.query.next === "string" ? route.query.next : "/"));

function resolveNextPath(rawPath: string | null) {
  if (!rawPath) return "/";
  if (!rawPath.startsWith("/") || rawPath.startsWith("//")) return "/";
  return rawPath;
}

onMounted(() => {
  if (errorParam.value) {
    error.value = `Đăng nhập Google thất bại: ${errorParam.value}`;
    return;
  }
  if (!accessToken.value) return;
  void (async () => {
    const loginError = await auth.loginWithToken(accessToken.value!, refreshToken.value);
    if (loginError) {
      error.value = loginError;
      return;
    }
    await router.replace(resolveNextPath(nextParam.value));
  })();
});
</script>

// web/src/app/connect/google/callback/page.tsx
"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/components/auth-context";

function GoogleCallbackInner() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const { loginWithToken } = useAuth();
  const [error, setError] = useState<string | null>(null);
  const accessToken = searchParams.get("access_token");
  const refreshToken = searchParams.get("refresh_token") ?? undefined;
  const errorParam = searchParams.get("error");

  useEffect(() => {
    if (errorParam) {
      setError("Đăng nhập Google thất bại: " + errorParam);
      return;
    }
    if (!accessToken) {
      return;
    }

    (async () => {
      const loginError = await loginWithToken(accessToken, refreshToken);
      if (loginError) {
        setError(loginError);
        return;
      }
      router.replace("/");
    })();
  }, [accessToken, refreshToken, errorParam, loginWithToken, router]);

  if (!accessToken && !errorParam) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-3">
          <p className="text-red-500 font-medium">Không nhận được token từ Google.</p>
          <button
            onClick={() => router.replace("/")}
            className="text-sm text-blue-600 hover:underline"
          >
            Quay về trang chủ
          </button>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-3">
          <p className="text-red-500 font-medium">{error}</p>
          <button
            onClick={() => router.replace("/")}
            className="text-sm text-blue-600 hover:underline"
          >
            Quay về trang chủ
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center space-y-3">
        <svg
          className="animate-spin mx-auto text-blue-600"
          xmlns="http://www.w3.org/2000/svg"
          width="28"
          height="28"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M21 12a9 9 0 1 1-6.219-8.56" />
        </svg>
        <p className="text-sm text-zinc-500">Đang xử lý đăng nhập...</p>
      </div>
    </div>
  );
}

export default function GoogleCallbackPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center">
          <svg
            className="animate-spin text-blue-600"
            xmlns="http://www.w3.org/2000/svg"
            width="28"
            height="28"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M21 12a9 9 0 1 1-6.219-8.56" />
          </svg>
        </div>
      }
    >
      <GoogleCallbackInner />
    </Suspense>
  );
}
